version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./psql:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  redis:
    restart: always
    image: redis:latest
    expose:
        - '6379'
    ports:
      - "6379:6379"
    depends_on:
      - db

  api:
    build: django-api/.
    image: django-api:latest
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django-api:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis

  image-classifier:
    image: django-api:latest
    command: celery -A photo_organizer worker -B
    depends_on:
      - api
volumes:
    psql:
    django-api: