# Generated by Django 3.2.8 on 2021-10-31 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('path', models.ImageField(upload_to='media/')),
                ('classification', models.TextField(blank=True)),
            ],
        ),
    ]
